#!/command/with-contenv bash
# shellcheck shell=bash

# Remove unbound service if not enabled
if [[ "${UNBOUND_ENABLED}" != true ]]; then
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/service-unbound
fi

# Remove tailscale service if not enabled
if [[ "${TS_ENABLED}" != true ]]; then
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/service-tailscale
fi

if [[ "${TS_ENABLED}" != true ]] || [[ "${TS_HEALTHCHECK_ENABLED}" != true ]]; then
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/service-healthcheck
fi

# shellcheck source=/dev/null
if [[ -f /etc/s6-overlay/init-hook-app ]]; then
    source /etc/s6-overlay/init-hook-app
fi
